### ISSUE TITLE
"Broken" zip

### ISSUE THREAD

**Issue by FakeShemp** [flathub/io.designer.GravitDesigner#20]
Is it just me or is the official zip download actually erroneous? It seems to be flagged multipart but isn't actually.

`unzip` can't handle it. What other options are there for handling invalid zip files in a flatpak sandbox?

**Comment by nahuelwexd** [comment]
I think the error is not in unzip or in the official zip, but in the command used to download it.

I have been experimenting, and if I download the zip with Google Chrome, then unzip can unzip it correctly. Instead, if I download it with wget, unzip fails saying that the zip is multipart. This made me curious, which led me to examine if they really are the same file, and...

```sh
❯ sha256sum GravitDesigner.zip # The zip that I downloaded with Chrome
a10a21d1231788e83b9014f46f64d64bd5a5a0bf216a031017b45fded4154dce  GravitDesigner.zip
❯ sha256sum ~/GravitDesigner.zip # The zip that I downloaded with wget
a242230572533ffe9c4745aa0081201f7577dd4f42836479f1f9e13429585c56  /home/nahuelwexd/GravitDesigner.zip
```

It seems that wget is failing to download the zip file.

**Comment by eszlari** [comment]
firefox:
```
$ file GravitDesigner.zip 
GravitDesigner.zip: Zip archive data, at least v2.0 to extract
```
curl / wget:
```
$ file GravitDesigner.zip 
GravitDesigner.zip: gzip compressed data, original size modulo 2^32 194662518 gzip compressed data, unknown method, extra field, has comment, encrypted, from FAT filesystem (MS-DOS, OS/2, NT), original size modulo 2^32 194662518
```

This was handled correctly, but @FakeShemp removed that for whatever reason?!

**Comment by FakeShemp** [comment]
I was not aware that it was actually gzipped specifically when wget'ted. I'll fix.

**Comment by eszlari** [comment]
> I was not aware that it was actually gzipped specifically when wget'ted. I'll fix.

Already done: https://github.com/flathub/io.designer.GravitDesigner/commit/2fdf99dc5c97e56923569597e1b586f2e659310c

**Comment by FakeShemp** [comment]
Thanks :)
