### ISSUE TITLE
Error when installing on Pop OS

### ISSUE THREAD

**Issue by kd2flz** [flathub/io.designer.GravitDesigner#30]
I get the following error when I attempt installation on Pop OS:
```
error: Wrong size for extra data https://designer.gravit.io/_downloads/linux/GravitDesigner.zip
error: Failed to install io.designer.GravitDesigner: Wrong size for extra data https://designer.gravit.io/_downloads/linux/GravitDesigner.zip
```
I have never seen this with a Flatpak before, so I'm not sure what could be causing it.

**Comment by hfiguiere** [comment]
This is #2 

tl;dr the vendor of this application doesn't want to cooperate.

**Comment by kd2flz** [comment]
To bad, but I understand.
________________________________

**Comment by hfiguiere** [comment]
just to be clear, having a solution would be great. That's why issue #2 is still open. It covers this.

**Comment by kd2flz** [comment]
Ok, thanks.

________________________________
