### ISSUE TITLE
GravitDesigner Flatpak will not install on Fedora 33

### ISSUE THREAD

**Issue by Sauron0** [flathub/io.designer.GravitDesigner#31]
I tried to install using the Discover app.  Failed twice with no error message.
Used command line to install.  Failed.

[Anubis@Fedora ~]$ sudo flatpak install flathub io.designer.GravitDesigner
[sudo] password for Anubis: 
Looking for matches…

io.designer.GravitDesigner permissions:
    ipc                  network       x11     dri
    file access [1]      tags [2]

    [1] home
    [2] proprietary

        ID                           Branch   Op  Remote   Download
 1. [✗] io.designer.GravitDesigner   stable   i   flathub  410.8 MB / 411.7 MB

Error: Wrong size for extra data https://designer.gravit.io/_downloads/linux/GravitDesigner.zip
error: Failed to install io.designer.GravitDesigner: Wrong size for extra data https://designer.gravit.io/_downloads/linux/GravitDesigner.zip

**Comment by hfiguiere** [comment]
This is a dupe of #2
