### ISSUE TITLE
Fails to launch with Nvidia

### ISSUE THREAD

**Issue by CWhyMedia** [flathub/io.designer.GravitDesigner#4]
When I attempt to launch Gravit Designer, I just get a black box, with this terminal output:

[gravit-designer.txt](https://github.com/flathub/io.designer.GravitDesigner/files/2338325/gravit-designer.txt)

I'm on CentOS 7.5 with a GTX 980, fully up to date with the proprietary Nvidia driver installed from ELRepo. Don't have graphical issues with any other software.

**Comment by CWhyMedia** [comment]
Oh... https://github.com/flatpak/flatpak/issues/138

**Comment by eszlari** [comment]
What's the output of:
```
$ nvidia-settings -g | grep "OpenGL version"

$ flatpak --gl-drivers
```

**Comment by CWhyMedia** [comment]
Turns out all I had to do was run "flatpak update". It's fixed now. Here's the output anyway, though: 

`OpenGL version string: 4.6.0 NVIDIA 390.87`

```
$ flatpak --gl-drivers
nvidia-390-87
default
host
```
