### ISSUE TITLE
Keeps failing to update: apply_extra script failed, exit status 256

### ISSUE THREAD

**Issue by Ryder17z** [flathub/io.designer.GravitDesigner#56]
`Error: While trying to apply extra data: apply_extra script failed, exit status 256`

This is happening on Manjaro 21.2.6

**Comment by hyphone** [comment]
Same issue with Fedora 35

**Comment by OliverLeitner** [comment]
having the same problem with something larger...

 lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
-----------------------------------------------------
flatpak update
Looking for updates…
Info: org.gnome.Sdk is end-of-life, with reason: The GNOME 3.34 runtime is no longer supported as of 14th August 2020. Please ask your application developer to migrate to a supported platform.
Info: org.gnome.Sdk.Locale is end-of-life, with reason: The GNOME 3.34 runtime is no longer supported as of 14th August 2020. Please ask your application developer to migrate to a supported platform.
Info: org.gnome.Platform is end-of-life, with reason: The GNOME 3.34 runtime is no longer supported as of 14th August 2020. Please ask your application developer to migrate to a supported platform.
Info: org.gnome.Platform.Locale is end-of-life, with reason: The GNOME 3.34 runtime is no longer supported as of 14th August 2020. Please ask your application developer to migrate to a supported platform.
Info: org.freedesktop.Platform.VAAPI.Intel is end-of-life, with reason: The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developer to migrate to a supported version
Info: org.freedesktop.Platform.GL.default is end-of-life, with reason: The Freedesktop SDK 19.08 runtime is no longer supported as of September 1, 2021. Please ask your application developerto migrate to a supported version


        ID                                                        Zweig             Op            Remote             Download
 1. [\] org.freedesktop.Platform.GL.nvidia-470-103-01             1.4               u             flathub              272,5 MB / 273,3 MB
        ID                                                        Zweig             Op            Remote             Download
 1. [✗] org.freedesktop.Platform.GL.nvidia-470-103-01             1.4               u             flathub            272,5 MB / 273,3 MB
        ID                                                        Zweig             Op            Remote             Download 1. [✗] org.freedesktop.Platform.GL.nvidia-470-103-01             1.4               u             flathub            272,5 MB / 273,3 MB
 2. [✗] org.freedesktop.Platform.GL.nvidia-470-129-06             1.4               u             flathub            272,1 MB / 273,0 MB
Warning: Während des Versuchs, zusätzliche Daten anzuwenden: Skript apply_extra ist fehlgeschlagen, Exit-Status 256
Warning: Während des Versuchs, zusätzliche Daten anzuwenden: Skript apply_extra ist fehlgeschlagen, Exit-Status 256
Updates complete.

**Comment by FastOSlinux** [comment]
https://github.com/flathub/io.designer.GravitDesigner/pull/57 solved
![image](https://user-images.githubusercontent.com/17401812/179036667-d9fbeaa1-c2c7-4d6d-a919-4ebcd00f19a0.png)

**Comment by Ryder17z** [comment]
Ah great. They completely ruined it now as not even the most basic functions work without signing in.
#garbage

(but yes. the issue is fixed.)
